[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.9
