[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_padding = true
